#!/usr/bin/env python3
"""Tests for deterministic injection-outcome attribution (attribute.py).

The point of #1: outcome signal must be generated by CODE, honestly and
conservatively. These encode the classification rules and the topical gate that
stops an unrelated correction from falsely marking a lesson harmful.

Run: python3 scripts/test_attribute.py
"""
import json
import os
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import attribute as A  # noqa: E402

INJ = 1000  # injection timestamp
ok_all = True


def check(name, got, want):
    global ok_all
    p = got == want
    ok_all &= p
    print(f"  [{'PASS' if p else 'FAIL'}] {name}: {got!r}")


def ev(ts, human, text, interrupt=False):
    return (ts, human, text, interrupt)


def main():
    print("classify (outcome, conservative harmful w/ topical gate):")
    terms = {"schema", "fetch"}

    # post-injection interruption -> harmful
    o, _ = A.classify([ev(1100, False, "", True)], INJ, terms)
    check("post-injection interruption -> harmful", o, "harmful")

    # on-topic post-injection correction -> harmful
    o, _ = A.classify([ev(1100, True, "no, the schema is wrong here")], INJ, terms)
    check("on-topic correction -> harmful", o, "harmful")

    # OFF-topic correction must NOT mark harmful (topical gate); and with no
    # success ack it is NOT helpful either -> neutral (the honest default)
    o, _ = A.classify([ev(1100, True, "no, make the button teal")], INJ, terms)
    check("off-topic correction -> neutral (not harmful, not helpful)", o, "neutral")

    # mere continuation is NOT helpful — that would manufacture positive signal
    o, _ = A.classify([ev(1100, True, "ok now add a second column")], INJ, terms)
    check("bare continuation -> neutral (no manufactured helpful)", o, "neutral")

    # on-topic success acknowledgement -> helpful
    o, _ = A.classify([ev(1100, True, "great, the schema fetch works now")], INJ, terms)
    check("on-topic success ack -> helpful", o, "helpful")

    # OFF-topic success ack must NOT credit this lesson (topical gate on helpful)
    o, _ = A.classify([ev(1100, True, "perfect, the CSS button is fixed now")], INJ, terms)
    check("off-topic success ack -> neutral (no manufactured helpful)", o, "neutral")

    # a success word that is negated / paired with a complaint is not helpful
    o, _ = A.classify([ev(1100, True, "the schema still doesn't work")], INJ, terms)
    check("negated/complaint on-topic -> not helpful", o != "helpful", True)

    # word boundary: 'unresolved' must NOT trip \\bresolved\\b
    o, _ = A.classify([ev(1100, True, "the schema is unresolved")], INJ, terms)
    check("'unresolved' does not match resolved", o != "helpful", True)

    # only PRE-injection activity -> neutral (nothing to judge)
    o, _ = A.classify([ev(500, True, "no, that's wrong")], INJ, terms)
    check("pre-injection only -> neutral", o, "neutral")

    # unreadable transcript -> neutral/no-transcript (defer, don't mis-judge)
    o, b = A.classify(None, INJ, terms)
    check("no transcript -> neutral", o, "neutral")
    check("no transcript basis", b, "no-transcript")

    # interruption BEFORE injection is ignored; on-topic ack after -> helpful
    o, _ = A.classify([ev(500, False, "", True), ev(1100, True, "that fixed the schema")], INJ, terms)
    check("pre-injection interrupt ignored, on-topic ack after -> helpful", o, "helpful")

    print("\nbump_counter (frontmatter integer increment / insert):")
    d = tempfile.mkdtemp()
    p = os.path.join(d, "L.md")
    open(p, "w").write("---\nid: L\nhelpful: 0\nharmful: 0\n---\nbody helpful: 99 (must not change)\n")
    check("bump existing helpful 0->1", A.bump_counter(p, "helpful"), 1)
    check("bump existing helpful 1->2", A.bump_counter(p, "helpful"), 2)
    txt = open(p).read()
    check("body 'helpful: 99' untouched", "body helpful: 99 (must not change)" in txt, True)
    check("frontmatter now helpful: 2", "helpful: 2" in txt, True)

    p2 = os.path.join(d, "L2.md")
    open(p2, "w").write("---\nid: L2\nscope: global\n---\nbody\n")
    check("insert absent harmful -> 1", A.bump_counter(p2, "harmful"), 1)
    check("harmful field inserted in frontmatter", "harmful: 1" in open(p2).read(), True)

    # non-integer/empty counters heal to 1 WITHOUT creating a duplicate key
    p3 = os.path.join(d, "L3.md")
    open(p3, "w").write("---\nid: L3\nhelpful:\nharmful: x\n---\nbody\n")
    check("heal empty helpful -> 1", A.bump_counter(p3, "helpful"), 1)
    check("heal garbage harmful -> 1", A.bump_counter(p3, "harmful"), 1)
    t3 = open(p3).read()
    check("no duplicate helpful key", t3.count("helpful:"), 1)
    check("no duplicate harmful key", t3.count("harmful:"), 1)

    print("\nconcurrency: N parallel attributions of the SAME global lesson lose no counts:")
    import re as _re
    import threading
    cd = tempfile.mkdtemp()
    st, les = os.path.join(cd, "state"), os.path.join(cd, "lessons")
    os.makedirs(st); os.makedirs(les)
    A.STATE, A.GLOBAL_LESSONS = st, les
    A.INJECTIONS = os.path.join(st, "injections.jsonl")
    A.EVENTS = os.path.join(st, "events.jsonl")
    A.ATTRIBUTED = os.path.join(st, "attributed.jsonl")
    A.LOCKFILE = os.path.join(st, "attribution.lock")
    lf = os.path.join(les, "gate-test.md")
    open(lf, "w").write("---\nid: gate-test\nhelpful: 0\nharmful: 0\n---\nbody\n")
    N = 16
    jobs = []
    with open(A.INJECTIONS, "w") as fh:
        for i in range(N):
            sid = f"s{i}"
            fh.write(json.dumps({"session": sid, "lesson": "gate-test", "ts": 1000,
                                 "matched": ["schema"], "project": ""}) + "\n")
            tp = os.path.join(cd, f"{sid}.jsonl")
            open(tp, "w").write(json.dumps({"timestamp": "2020-01-01T00:00:00Z", "type": "user",
                "message": {"content": "the schema works now"}}) + "\n")
            jobs.append((sid, tp))
    threads = [threading.Thread(target=A.attribute_session, args=(sid, tp)) for sid, tp in jobs]
    for t in threads:
        t.start()
    for t in threads:
        t.join()
    hv = int(_re.search(r"helpful:\s*(\d+)", open(lf).read()).group(1))
    check(f"helpful == {N} (no lost updates under {N} concurrent bumps)", hv, N)
    check(f"attributed.jsonl has exactly {N} rows (no double-attribution)",
          sum(1 for _ in open(A.ATTRIBUTED)), N)

    print("\n" + ("ALL PASS" if ok_all else "FAILURES ABOVE"))
    sys.exit(0 if ok_all else 1)


if __name__ == "__main__":
    main()
